### ISSUE TITLE
Parser doesn't detect custom input date format

### ISSUE THREAD

**Issue by lokesh-krishna** [cbarrete/tree-sitter-ledger#15]
Is it intentional for there to be no highlighting when using a custom input date format? I'm presently using DD/MM/YY but can only get highlighting to work when using YYYY/MM/DD.

**Comment by cbarrete** [comment]
I'm pretty sure, from trying it in ledger, looking at the docs and reading the (admittedly old and outdated) `grammar.y` that anything that isn't `YYYY.MM.DD` isn't legal.

Are you using another program like hledger? If not, can you post a short snippet of a transaction with `DD/MM/YY` formatting that is accepted by ledger?

**Comment by lokesh-krishna** [comment]
I'm using ledger and I have the following alias in my `.zshrc`:
```sh
alias ledger='ledger --input-date-format "%d/%m/%y" -f ~/storage/shared/sync/ledger.dat'
```

I input transactions in my ledger file as follows
```ledger
14/07/21 Example transaction
   Assets:Account1      ₹500
   Assets:Account2
```

This is accepted by ledger and it returns balance and registers without any errors.

**Comment by cbarrete** [comment]
I see, I didn't think about that. The issue is that we can't predict what the user might use here. For example `2020Valid01Date01` is correct when using `--input-date-format "%YValid%dDate%m"` and one can even omit e.g. the day entirely in their format expression.

https://github.com/ledger/vim-ledger is much more permissive on that front, but I want to keep this parser stricter so that we can build things on top of it later and actually extract the (effective) date.

https://www.ledger-cli.org/3.0/doc/ledger3.html#Date-and-Time-Format-Codes shows how complex date/time format codes can get and I don't think that we should (try to) support all "sensible" combinations.

Of course you can always hack the grammar for yourself (see `_single_date: $ => /\d{4}[-\.\/]\d{2}[-\.\/]\d{2}/,`) to fit your needs.

**Comment by lokesh-krishna** [comment]
I see. I wasn't aware of the complexity involved and have actually already switched over to the default format because I didn't want to miss out on the highlighting. 

Thanks for your detailed response :)
