### ISSUE TITLE
MM-DD not supported as date format

### ISSUE THREAD

**Issue by pickfire** [cbarrete/tree-sitter-ledger#17]
ledger accepts MM-DD as date format but it wasn't accepted by tree-sitter-ledger here. But YYYY-MM-DD seemed to work but that is way more troublesome to type so I use MM-DD, can we support that as well?

Maybe change this line here?
https://github.com/cbarrete/tree-sitter-ledger/blob/72319504776f14193472a6ad14abec0af0225cbe/grammar.js#L208
to `(\d{4}[-\.\/])?\d{2}[-\.\/]\d{2}`

**Comment by cbarrete** [comment]
Please see https://github.com/cbarrete/tree-sitter-ledger/issues/15.

Essentially, the issue is that there are tons of possible date formats and we can't support anything a user might use. People like to use YYYY-MM, YY-MM, MM-DD in your case, and change the order of year, month and day as well. Your suggestion unfortunately wouldn't cover the preferences of a lot of people.

I'm still considering alternatives but enumerating all possible permutations sounds like a bad idea to me.

In the meantime, I suggest avoiding typing the dates altogether with a custom mapping, possibly using a snippets plugin. I personally do

```lua
        s('date', sn(1, {
            t(os.date('%Y-%m-')),
            i(1, os.date('%d')),
        })),
```

using https://github.com/L3MON4D3/LuaSnip, which is very convenient, but you could also do something simpler and just insert the current date with an `inoremap`, or more complicated and get part of the date from your filename, depending on your use-case.

Snippet plugin alternatives include:
- https://github.com/hrsh7th/vim-vsnip
- https://github.com/sirver/UltiSnips
- https://github.com/norcalli/snippets.nvim

**Comment by pickfire** [comment]
I don't do snippets, I type them out. Showing the year is redundant and does not help much, I don't want to read the `2021-` even because the file is only for 2021 entries. If I do snippet I will still only want `MM-DD` for the year and at the end of the year I will re-export it with the year (`YYYY-MM-DD`) again for archival purposes.

I did see #15, but MM-DD should be common, I don't see why can't we enumerate the date support, it's just adding a `?` and a group here.

Also, I don't use neovim to edit, I use kakoune (probably helix later) and I didn't check for snippets tool, at least for me I didn't use snippets because typing it out is faster.

Or why not just accept anything for the date, at least it will highlight the date correctly?

**Comment by cbarrete** [comment]
>MM-DD should be common

And yet you're the first to ask for it so not really.

>it's just adding a ? and a group here

No, it doesn't handle `DD/MM/YY` or `DD/MM/YYYY`

**Comment by cbarrete** [comment]
>MM-DD should be common

And yet you're the first to ask for it so not really.

>it's just adding a ? and a group here

No, it doesn't handle `DD/MM/YY` or `DD/MM/YYYY` which are also (more) popular.

>I don't use neovim to edit

My bad then

>Or why not just accept anything for the date, at least it will highlight the date correctly?

I might do that at some point but it's nice to have something a bit stricter, it's helpful when you make a typo. Also by splitting it into further and focusing on ISO 8601, we could enable tools to access the date and do nice things with them by actually understanding it as a date rather than a string.

**Comment by pickfire** [comment]
Then I guess there are no other way to add this unless I fork it and create a `MM-DD` version?

**Comment by cbarrete** [comment]
Not anymore :)
